### ISSUE TITLE
numpy versions

### ISSUE THREAD

**Issue by mvzn** [microsoft/fadtk#32]
Hello,

I am trying to use encodec for evaluating FAD with this repo.
While trying to install it to Google Colab there are problems with numpy versions.

Specifically:
albucore 0.0.13 requires numpy<2,>=1.24.4, but you have numpy 1.23.5 which is incompatible.
albumentations 1.4.14 requires numpy>=1.24.4, but you have numpy 1.23.5 which is incompatible.
chex 0.1.86 requires numpy>=1.24.1, but you have numpy 1.23.5 which is incompatible.
pandas-stubs 2.1.4.231227 requires numpy>=1.26.0; python_version < "3.13", but you have numpy 1.23.5 which is incompatible.
torchtext 0.18.0 requires torch>=2.3.0, but you have torch 2.1.2 which is incompatible.

**Comment by hykilpikonna** [comment]
This error appears because of a versioning conflict with your existing packages.

None of the packages `albucore`, `albumentations`, `chex`, `pandas-stubs`, and `torchtext` are in the dependency tree of our fadtk. They are packages that you installed separately, which might be incompatible due to the numpy version requirements.

Also, this is a warning, not an error. The python community is especially notorious for bad dependency versioning practices, and I honestly don't think using numpy 1.23.5 will break anything for the other packages you installed.
