### ISSUE TITLE
Accessing score when running on custom baseline

### ISSUE THREAD

**Issue by MikeMpapa** [microsoft/fadtk#9]
Thanks for this great repo! Very good work!

 I am trying to run on my own baseline but I don't think the output is being stored anywhere. 
How can I access FAD scores once I run on my baseline ? 

Options to store output into csv and also -inf and -indiv flags don't seem to work in the 'Example 3' case.

Thanks again!

**Comment by hykilpikonna** [comment]
Since the FAD / FAD∞ score between a baseline and an evaluation set is just a single number, it was printed to standard output.

![image_2023-12-23_01-38-37](https://github.com/microsoft/fadtk/assets/22280294/b791b7c0-d779-4efa-9c62-6f47cf5ead25)

However, since you brought this up, I just added an option to append these single-value results to an output CSV file. Now you can specify a CSV path as the last argument for non-individual FAD / FAD∞ as well.

![image_2023-12-23_01-58-51](https://github.com/microsoft/fadtk/assets/22280294/e09e3e01-f5ec-44e4-a690-b6d4700e09ee)


Also, I just tested that `--inf` and `--indiv` flags both work under the Example 3 case as shown below. Please make sure you're using the command correctly with two dashes before the flag (i.e. `--inf`). I noticed that in your issues, you were using a single dash to specify the argument (i.e. `-inf`), which would be incorrect.

![image_2023-12-23_01-41-32](https://github.com/microsoft/fadtk/assets/22280294/fd91305a-0d7c-457d-86a8-ad4ad1283c1a)
